# Generated by Django 4.0.6 on 2022-10-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.CharField(max_length=100)),
                ('Participent_Name', models.CharField(max_length=100)),
                ('Participent_Address', models.CharField(max_length=100)),
            ],
        ),
    ]
